spring.datasource.url=jdbc:postgresql://localhost:5432/school-lab
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

integration.weatherClient.accessKey = a1c466c85817cca17ef1f3d022e783c9